baseURL: 'https://hartje.io/'
languageCode: en-us
title: hartje.io

contentDir: content/en
custom_css: ["css/terminal.css"]
gcs_engine_id: "011737558837375720776:fsdu1nryfng"

disqusShortname: hartje-dot-io

taxonomies:
  tag: tags
  category: categories

params:
  links:
    user:
    - name: Linkedin
      url: https://linkedin.com/in/ryan-hartje/
      icon: "fab fa-linkedin"
    - name: Twitter
      url: https://twitter.com/xoxodeadbeef
      icon: "fab fa-twitter"
  ui:
    footer_about_disable: true

markup:
  goldmark:
    renderer:
      unsafe: true

# hugo module configuration
module:
  imports:
  # - path: github.com/google/docsy
  # - path: github.com/google/docsy/dependencies
  - path: github.com/FortAwesome/Font-Awesome

theme: terminal
